import type { Metadata } from "next";
import "./globals.css";

// Import do Toaster do Sonner
import { Toaster } from "sonner";

// Apollo Client

import { ApolloProviderClient } from "@/lib/apollo/ApolloProviderCliente";

// caminho do seu apollo-client.ts

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloProviderClient>
          {children}
          <Toaster position="bottom-right" richColors />
        </ApolloProviderClient>
      </body>
    </html>
  );
}
